### ISSUE TITLE
Readme Error - ConfigHelper requires a parameter for make()

### ISSUE THREAD

**Issue by ghost** [JumpTwentyFour/laravel-coding-standards#18]
``` $ecsConfig->skip(array_merge(ConfigHelper::make()->getParameter(Option::SKIP)```

in the readme, we have the above portion of code.  There is a slight error in this - ConfigHelper::make() requires an ECSConfig parameter - in this case, passing $ecsConfig into that make as the parameter resolves it:

```$ecsConfig->skip(array_merge(ConfigHelper::make($ecsConfig)->getParameter(Option::SKIP)```

we are also missing a couple of use statements for UnusedParameterSniff and CamelCapsFunctionNameSniff.

**Comment by AlexJump24** [comment]
Fix for readme here https://github.com/JumpTwentyFour/php-coding-standards/pull/36

**Comment by ghost** [comment]
awesome, i'll close this then :)
